apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cyy95dxmo-python 
  janus-idp.io/tekton: cyy95dxmo-python
  backstage.io/kubernetes-id: cyy95dxmo-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cyy95dxmo-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  