apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: cyy95dxmo-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-bee9e46339.shoh.p3.openshiftapps.com/rhtap/rhtap-qe:51653309ee10a8f9e3034d7510664dd25f9e959f@sha256:69e097839000bbf622e8d4a6faf3e92c574eebd8607e832d4818a4bdc2767d1e
          name: container-image
