apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cyy95dxmo-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cyy95dxmo-python 
  name: cyy95dxmo-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cyy95dxmo-python 
